name: Pages

on:
  push:
    branches:
      - hexo-source  # default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          # Your GitHub Token
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The repository the action should deploy to
          PUBLISH_REPOSITORY: saintsitive-dev/saintsitive-dev.github.io
          BRANCH: master
          CNAME: saintsitive.space
